### ISSUE TITLE
kepclean is still available on the command line

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/pyke#153]
But I don't think we support it anymore? If you try to run it you get an error.

`Traceback (most recent call last):
  File "/Users/ch/anaconda/bin/kepclean", line 11, in <module>
    load_entry_point('pyketools', 'console_scripts', 'kepclean')()
  File "/Users/ch/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ch/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2750, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'kepclean') not found
`

**Comment by christinahedges** [comment]
I think this is what cleans out bad quality flags on the command line though, this would be useful to have?

**Comment by mirca** [comment]
I thought we are supporting it? `kepclean` was added in #66.

cc @barentsen

**Comment by mirca** [comment]
If we are supporting it, we should definitely add an entry here: http://pyke.keplerscience.org/api/index.html

**Comment by mirca** [comment]
@christinahedges here it works fine:

```
➜ kepclean --help
usage: kepclean [-h] [--outfile OUTFILE] [--zero] [--overwrite] [--verbose]
                [--logfile LOGFILE]
                infile

Remove unwanted time ranges from Kepler time series data

positional arguments:
  infile                Name of input file

optional arguments:
  -h, --help            show this help message and exit
  --outfile OUTFILE     Name of FITS file to output. If None, outfile is
                        infile-kepclean. (default: None)
  --zero                Zero any remaining NaN values?
  --overwrite           Overwrite output file?
  --verbose             Write to a log file?
  --logfile LOGFILE, -l LOGFILE
                        Name of ascii log file (default: kepclean.log)
```
