### ISSUE TITLE
`kepsff` raises ValueError in K2 aperture photometry tutorial

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/PyKE#72]
When trying out the [K2 aperture photometry tutorial](http://pyke.keplerscience.org/en/latest/tutorials/aperture-photometry-in-k2.html) I encounter the following exception:

```
$ kepsff ktwo202073445-c00_lpd-targ-kepextract-kepclip-kepflatten.fits --datacol DETSAP_FLUX --stepsize 5. --npoly_ardx 4 --sigma_dsdt 10. --overwrite
  0%|                                                                                                                                               | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/gb/bin/anaconda/bin/kepsff", line 11, in <module>
    load_entry_point('pyketools', 'console_scripts', 'kepsff')()
  File "/home/gb/dev/PyKE/pyke/kepsff.py", line 774, in kepsff_main
    args.logfile)
  File "/home/gb/dev/PyKE/pyke/kepsff.py", line 701, in kepsff
    instr[1].data.field('SAP_FLUX')[t1:t2] /= cfac
ValueError: operands could not be broadcast together with shapes (244,) (8,) (244,) 
```

**Comment by mirca** [comment]
fixed in [72746b](https://github.com/KeplerGO/PyKE/commit/72746bba57988bde266d47ba24e5c5150fb45057)

**Comment by barentsen** [comment]
Schweet :strawberry:
